print()
print("Example 1")
text = input("Enter a text: ")
length = len(text)
print(f"\nText length: {length} characters")
print("In uppercase:", text.upper())
print("In lowercase:", text.lower())

print()
print("Example 2")
from datetime import datetime
current_year = datetime.now().year
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
birth_year = int(input("Enter your birth year: "))
age = current_year - birth_year
print("\nYour personal profile:")
print(f"First name: {first_name}")
print(f"Last name: {last_name}")
print(f"Birth year: {birth_year}")
print(f"Age: {age} years old")

print()
print("Example 3")
sentence = input("Enter a sentence: ")
words = sentence.split()
word_count = len(words)
longest_word = max(words, key=len)
print(f"\nNumber of words: {word_count}")
print(f"Longest word: {longest_word}")
